bot:
  # Log level. Recommended: 200 (info)
  log_level: 200

reddit:

  # reddit login data
  client_id: 'client_id'
  secret_key: 'secret_key'
  redirect_uri: 'redirect_uri'
  username: 'username'
  password: 'password'

  # Should be left as "submit, read"
  scopes: ['submit', 'read']

  # Domains you don't want the bot to take care of. Wildcards accepted.
  banned_domains: ['imgur.com',
                   '*.imgur.com',
                   'twitter.com',
                   'youtube.com',
                   'reddit.com',
                   '*.reddit.com',
                   '*.redditmedia.com',
                   'self.*',
                   'youtube.com',
                   'youtu.be',
                   '*.youtube.com',
                   'storify.com',
                   'buzzfeed.com',
                   'radiocut.fm',
                   '*.radiocut.fm',
                   'vid.me'
                   ]

  # Subreddits you want to monitor
  subreddits: ['empleadoEstatalBot']

  # Subreddits you want the bot comments to be distinguished and sticked
  # (You HAVE to be a mod and your account MUST HAVE the 'post' permission)
  distinguishable: ['empleadoEstatalBot']

newspaper_processor:

  # URL Shorteners you want to resolve (reddit doesn't like those services)
  url_shorteners: ['t.co',
                   'goo.gl',
                   'bit.ly'
                   ]

  # Bot signature. In HTML or markdown
  signature: 'signature'

  # Max reddit comment length. Right now is 10000. Set a conservative value like 9000.
  max_length: 9000

database:

  #DB connection information
  host: '127.0.0.1'
  name: 'db'
  user: 'dbuser'
  pass: 'dbpass'
